### ISSUE TITLE
Why a dump, and not put the files in the repository itself?

### ISSUE THREAD

**Issue by eyy** [projectbenyehuda/public_domain_dump#1]
(רעיון מצוין, ד"א. תודה)

**Comment by abartov** [comment]
Because GitHub discourages uploading files larger than 50MB (which these are) to repositories, especially when they won't have reasonable deltas.  The recommended route is uploading these ZIP archives as "releases", so that's what I've done.

**Comment by eyy** [comment]
Not the .zip file, upload the .html files. None of these are more then a few MBs.
