### ISSUE TITLE
Sub folders per content type

### ISSUE THREAD

**Issue by oatmealm** [projectbenyehuda/public_domain_dump#4]
Would it be too much to ask to put each text item in a sub folder under each author according to its type: עיון, פרוזה, שירה etc? 

I'm aware of the legend cvs file and currently using it to extract the content I need, but thought it might be redundant to do. 

Thanks

**Comment by abartov** [comment]
While it would save some work for your use case, it would *add* work for others. So I don't see a net gain.

**Comment by oatmealm** [comment]
Might be useful to others, I'm assuming, since you have a workflow in place, would it be possible to simply generate an extra archive?

10d
