### ISSUE TITLE
סידור המאגר בצורה נוחה יותר

### ISSUE THREAD

**Issue by zevisvei** [projectbenyehuda/public_domain_dump#5]
אני יצרתי סקריפט שיסדר את הקבצים, אחד שיכניס את הקבצים לתיקיות לפי מחבר [בקבצים שזה מופיע בהם בשורה 10]
והשני שישנה את שם הקובץ לטקסט שמופיע בשורה 5 של כל קובץ 
השאלה היא למה לא עשיתם את זה מלכתחילה והאם ישנם פרמטרים שניתן לסדר בעזרתם בצורה טובה יותר [מדובר בסקריפט פייתון]

[בן_יהודה_1.txt](https://github.com/projectbenyehuda/public_domain_dump/files/12566880/_._1.txt)
[בן_יהודה_2.txt](https://github.com/projectbenyehuda/public_domain_dump/files/12566881/_._2.txt)

**Comment by abartov** [comment]
שלום לך.
תודה על ששיתפת את הסקריפטים. אם תרצה/י לשחררם תחת רשיון חופשי, נוכל להוסיף אותם למאגר הזה, לנוחות משתמשים אחרים.

לשאלתך מדוע לא ארגנּו כך את הדאמפ מלכתחילה: יש יצירות מורכבות יותר מאחרות – יצירות בעלות יותר ממחבר אחד, למשל – וכן, יצירות שמעניין יותר המתרגם שלהם מאשר המחבר שלהן, מבחינת מציאת היצירה. לא רצינו להתמודד עם המורכבויות הללו בדאמפ, אלא לעשות את המינימום שינגיש את החומר לשימושם של אחרים, שיוכלו לבצע בו כל עיבוד שירצו, בדיוק כשם שעשית את/ה.

**Comment by zevisvei** [comment]
בוודאי, זה לשימוש חופשי
אגב יצרתי סקריפט שיסדר את הכל לפי קטגוריות ובתוך התיקיות של הקטגוריות לפי יוצרים [מנתח את קובץ הCSV]
יש כמה שגיאות בכמה קבצים, במקרה כזה הסקריפט עוקף עליהם, ניתן למחוק אחר כך את התיקיות הריקות על ידי סקריפט נוסף, מצרף את הסקריפטים:
[בן_יהודה_אקסל7.txt](https://github.com/projectbenyehuda/public_domain_dump/files/12567687/_._.7.txt)
[1_מחיקת_תיקיות_ריקות.txt](https://github.com/projectbenyehuda/public_domain_dump/files/12567689/1_._._.txt)
מדובר בסקריפט python כך שצריך לשנות את הסיומת, משום מה גיטהאב לא נותנים לצרף קבצים בסיומת py
יש לציין שאחרי הרצת הסקריפט חסרים 153 קבצים, כנראה בגלל שיש יותר מקובץ אחד באותה תיקייה עם אותו השם, אם יהיה לי זמן אני אתקן את זה

**Comment by zevisvei** [comment]
עריכה:
זאת באמת היתה בעיה של קבצים עם אותו השם, בדקתי מלמעלה וחלקם קבצים כפולים וחלקם שונים, מצרף סקריפט מעודכן:
[בן_יהודה_אקסל8.txt](https://github.com/projectbenyehuda/public_domain_dump/files/12568111/_._.8.txt)
מצרף גם רשימה של הקבצים עם השמות הכפולים:
[רשימת קבצים כפולים.txt](https://github.com/projectbenyehuda/public_domain_dump/files/12568113/default.txt)
אגב ישנם הרבה קבצים שלא הועברו לתיקיות ושמם לא שונה מכיון שהם לא מופיעים בקובץ האקסל, מצרף רשימה:
[מסמכים שלא קיימים בקובץ האקסל.txt](https://github.com/projectbenyehuda/public_domain_dump/files/12568116/default.txt)
